name: Build RC and Upload

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: github-runner-dune
    env:
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      VERSION_NAME: ${{ github.ref_name }}

    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          lfs: true

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Decode and place keystore
        if: env.KEYSTORE_BASE64 != ''
        run: |
          mkdir -p sign
          echo "${{ env.KEYSTORE_BASE64 }}" | base64 --decode > sign/keystore.jks

      - name: Run lint check
        run: ./gradlew lint

      - name: Run unit tests
        run: ./gradlew testDemoReleaseUnitTest

      - name: Build DEMO release APK
        run: ./gradlew assembleDemoRelease

      - name: Rename DEMO release APK with version name
        run: |
          # Extract version name from branch ref
          VERSION_REF="${GITHUB_REF##*/}"   # gets '2025.11-2' from 'refs/heads/release/2025.11-2'
          APK_PATH=$(ls app/build/outputs/apk/demo/release/*.apk | head -n 1)
          mv "$APK_PATH" "app/build/outputs/apk/demo/release/demo_release_${VERSION_REF}_RC.apk"

      - name: Upload DEMO release APK
        uses: actions/upload-artifact@v4
        with:
          name: demo-release-apk
          path: app/build/outputs/apk/demo/release/demo_release_*_RC.apk
          retention-days: 90
